force-app/main/default/objects/Account/fields/BirthDate__c.field-meta.xml
<CustomField>
    <fullName>BirthDate__c</fullName>
    <label>BirthDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <description>External Id</description>
    <displayFormat>Ac-{0000}</displayFormat>
    <inlineHelpText>External ID for REST integration</inlineHelpText>
    <label>ExternalID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>FirstName</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>Subscription object to hold the data about Subscription start and end dates etc.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Subscription End Date</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Subscription Start Date</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/SubscriptionRestEndpoint.cls
@RestResource(urlMapping='/ActiveSubscriptions/*')
global with sharing class SubscriptionRestEndpoint {
    @HttpGet
    global static SubscriptionsWrapper getSubscriptions() {
    RestRequest req = RestContext.request;
    RestResponse res = RestContext.response;
    SubscriptionsWrapper response = new SubscriptionsWrapper();

    // Get the ExternalID from the end of the URL
    String acctExternalId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);

    List<Subscription__c> activeSubscriptions = [SELECT Account__r.FirstName__c, Account__r.LastName__c, Account__r.BirthDate__c, Name, Start_Date__c, End_Date__c 
                                                     FROM Subscription__c
                                                    WHERE Account__r.ExternalID__c = :acctExternalId
                                                      AND  Start_Date__c < TODAY
                                                      AND  End_Date__c   > TODAY];
    
    if(activeSubscriptions != null && activeSubscriptions.size() > 0) {
            response.subs   = activeSubscriptions;
            response.status = 'Success';
            response.message = 'These are the active subscriptions for the account.';
        }
    else {
            response.subs = null;
            response.status = 'Error';
            response.message = 'There are No active subscriptions for this account.';
        }

        return response;
    }

    global class SubscriptionsWrapper {
        public List<Subscription__c>   subs;
        public String   status;
        public String   message;

        public SubscriptionsWrapper(){}
    }
}